### ISSUE TITLE
Don't make users input a credit card number or bank routing number

### ISSUE THREAD

**Issue by brookeangel** [edwin-lai/helping-hand#1]
Yes, in reality we'd want that... but if you ever want an employer to test out your form you might not want to even have that field there, lest they think you're running an elaborate scheme to rob them

**Comment by brookeangel** [comment]
Yeah, definitely do not integrate real money into the project. :) It would be a cool thing to do in the future, but it is a feature that employers are not likely to test (and in fact will find sketchy)

**Comment by edwin-lai** [comment]
Replace cash with HappyCoins or something similar then?

**Comment by edwin-lai** [comment]
I have replaced real money with CareCoins and modified the database schema so that the user's financial information is no longer stored. Also, the wireframes have been adjusted accordingly. Finally, I have removed the withdrawal feature, since it would be pointless when dealing with CareCoins.
